/**
 * @copyright Copyright © 2025 Andrew Monson. All rights reserved.
 * @author    Andrew Monson <andrew.monson@elevate-digital.com>
 */

import path from "node:path";

import { readTextFile } from "../lib/fs.js";

/**
 * Get the default PROJECT_CONTEXT.md template content.
 *
 * @param projectName - Name of the project (optional, will be inferred if not provided)
 * @returns Template content
 */
export function getProjectContextTemplate(projectName?: string): string {
    const name = projectName || "this project";
    const today = new Date().toISOString().split("T")[0];

    return `Last Updated: ${today}

# Project Context: ${name}

> **This is the authoritative project context.** This file is tracked in git and updated as part of PRs. It represents how the project is *meant* to work, as approved by lead developers.
>
> For local operational context (working memory), see \`.ai/context/repo_context/REPO_CONTEXT.md\`.

## 1. Repo overview

- **What this repo is:** [Describe the project]
- **Primary use-case(s):** [List main use cases]
- **Key users or stakeholders:** [Who uses this?]
- **License:** [License type]

## 2. Quickstart (local dev)

### Prerequisites
- [List required tools/versions]

### Setup steps
\`\`\`bash
[Setup commands]
\`\`\`

### Run commands
\`\`\`bash
[How to run the project]
\`\`\`

### Smoke check
It works when: [Describe how to verify it's working]

## 3. Commands cheat sheet

| Task | Command |
|------|---------|
| [Task] | [Command] |

## 4. Key directories & ownership

- \`path/\` — [Purpose] — [Notable files]

## 5. Architecture

### Major components / services
[Describe major components]

### Boundaries and responsibilities
[Describe boundaries]

### Data flow
[Describe data flow, include diagram if helpful]

## 6. Configuration

### Environment variables
- \`VAR_NAME\` — [Purpose]

### Configuration files
| File | Purpose |
|------|---------|
| [File] | [Purpose] |

## 7. Testing

### Test types present
- [Unit / Integration / E2E]

### How tests run locally
\`\`\`bash
[Test commands]
\`\`\`

### How tests run in CI
[CI test process]

### Known slow, flaky, or risky areas
[Any test concerns]

## 8. Build & release

### Build outputs and artifacts
[What gets built]

### Versioning approach
[How versioning works]

### Release or deployment flow
[High-level release process]

## 9. Risk register

### Footguns
[Things that can go wrong]

### Sharp edges
[Non-obvious gotchas]

### Migration or refactor risks
[Known risks]

### "Don't do X because Y"
[Important warnings]

## 10. Open questions / assumptions

### Unknowns
[Things we don't know yet]

### Assumptions made during discovery
[Assumptions that were made]

### Items needing confirmation
[Things that need to be verified]

---

*This file is maintained as part of the codebase. Update it when making impactful changes to setup, architecture, workflows, or APIs.*
`;
}

/**
 * Derive PROJECT_CONTEXT.md content from existing REPO_CONTEXT.md.
 *
 * @param repoContextPath - Path to REPO_CONTEXT.md (default: ".ai/context/repo_context/REPO_CONTEXT.md")
 * @param repoRoot - Root directory of the repository (defaults to process.cwd())
 * @returns Derived content or null if REPO_CONTEXT.md doesn't exist
 */
export async function deriveProjectContextFromRepoContext(
    repoContextPath: string = ".ai/context/repo_context/REPO_CONTEXT.md",
    repoRoot?: string,
): Promise<string | null> {
    const root = repoRoot ?? process.cwd();
    const fullPath = path.resolve(root, repoContextPath);

    try {
        const content = await readTextFile(fullPath);

        // Extract the main content (skip the "Last Updated" line and any footer)
        const lines = content.split("\n");
        let startIndex = 0;
        let endIndex = lines.length;

        // Find where the actual content starts (after "Last Updated" line)
        for (let i = 0; i < lines.length; i++) {
            if (lines[i].startsWith("# ")) {
                startIndex = i;
                break;
            }
        }

        // Find footer (usually starts with "---" or "*Generated by")
        for (let i = lines.length - 1; i >= 0; i--) {
            if (lines[i].startsWith("---") || lines[i].includes("*Generated by")) {
                endIndex = i;
                break;
            }
        }

        const mainContent = lines.slice(startIndex, endIndex).join("\n").trim();

        // Transform the title and add authoritative note
        const transformed = mainContent
            .replace(/^# Repository Context:/, "# Project Context:")
            .replace(/^# Repository Context /, "# Project Context ");

        // Get today's date
        const today = new Date().toISOString().split("T")[0];

        // Build the final content with authoritative header
        return `Last Updated: ${today}

${transformed}

---

> **This is the authoritative project context.** This file is tracked in git and updated as part of PRs. It represents how the project is *meant* to work, as approved by lead developers.
>
> For local operational context (working memory), see \`.ai/context/repo_context/REPO_CONTEXT.md\`.
>
> *Initial content derived from REPO_CONTEXT.md on ${today}. Review and update as needed.*
`;
    } catch {
        // File doesn't exist or can't be read
        return null;
    }
}

/**
 * Get PROJECT_CONTEXT.md content, deriving from REPO_CONTEXT.md if available, otherwise using template.
 *
 * @param repoContextPath - Path to REPO_CONTEXT.md (default: ".ai/context/repo_context/REPO_CONTEXT.md")
 * @param repoRoot - Root directory of the repository (defaults to process.cwd())
 * @param projectName - Name of the project (optional)
 * @returns PROJECT_CONTEXT.md content
 */
export async function getProjectContextContent(
    repoContextPath: string = ".ai/context/repo_context/REPO_CONTEXT.md",
    repoRoot?: string,
    projectName?: string,
): Promise<string> {
    // Try to derive from existing REPO_CONTEXT.md
    const derived = await deriveProjectContextFromRepoContext(repoContextPath, repoRoot);
    if (derived) {
        return derived;
    }

    // Fall back to template
    return getProjectContextTemplate(projectName);
}
