/**
 * @copyright Copyright © 2025 Andrew Monson. All rights reserved.
 * @author    Andrew Monson <andrew.monson@elevate-digital.com>
 */

import { readFileSync } from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

import { readTextFile } from "../lib/fs.js";

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

// Load markdown template at module initialization
const PROJECT_CONTEXT_TEMPLATE = readFileSync(path.join(__dirname, "projectContext", "template.md"), "utf8");

/**
 * Simple template replacement function.
 * @param template
 * @param vars
 */
function replaceTemplateVars(template: string, vars: Record<string, string>): string {
    return template.replace(/\$\{(\w+)\}/g, (_, key) => vars[key] ?? `\${${key}}`);
}

/**
 * Get the default PROJECT_CONTEXT.md template content.
 *
 * @param projectName - Name of the project (optional, will be inferred if not provided)
 * @returns Template content
 */
export function getProjectContextTemplate(projectName?: string): string {
    const name = projectName || "this project";
    const today = new Date().toISOString().split("T")[0];

    return replaceTemplateVars(PROJECT_CONTEXT_TEMPLATE, {
        projectName: name,
        today,
    });
}

/**
 * Derive PROJECT_CONTEXT.md content from existing REPO_CONTEXT.md.
 *
 * @param repoContextPath - Path to REPO_CONTEXT.md (default: ".ai/context/repo_context/REPO_CONTEXT.md")
 * @param repoRoot - Root directory of the repository (defaults to process.cwd())
 * @returns Derived content or null if REPO_CONTEXT.md doesn't exist
 */
export async function deriveProjectContextFromRepoContext(
    repoContextPath: string = ".ai/context/repo_context/REPO_CONTEXT.md",
    repoRoot?: string,
): Promise<string | null> {
    const root = repoRoot ?? process.cwd();
    const fullPath = path.resolve(root, repoContextPath);

    try {
        const content = await readTextFile(fullPath);

        // Extract the main content (skip the "Last Updated" line and any footer)
        const lines = content.split("\n");
        let startIndex = 0;
        let endIndex = lines.length;

        // Find where the actual content starts (after "Last Updated" line)
        for (let i = 0; i < lines.length; i++) {
            if (lines[i].startsWith("# ")) {
                startIndex = i;
                break;
            }
        }

        // Find footer (usually starts with "---" or "*Generated by")
        for (let i = lines.length - 1; i >= 0; i--) {
            if (lines[i].startsWith("---") || lines[i].includes("*Generated by")) {
                endIndex = i;
                break;
            }
        }

        const mainContent = lines.slice(startIndex, endIndex).join("\n").trim();

        // Transform the title and add authoritative note
        const transformed = mainContent
            .replace(/^# Repository Context:/, "# Project Context:")
            .replace(/^# Repository Context /, "# Project Context ");

        // Get today's date
        const today = new Date().toISOString().split("T")[0];

        // Build the final content with authoritative header
        return `Last Updated: ${today}

${transformed}

---

> **This is the authoritative project context.** This file is tracked in git and updated as part of PRs. It represents how the project is *meant* to work, as approved by lead developers.
>
> For local operational context (working memory), see \`.ai/context/repo_context/REPO_CONTEXT.md\`.
>
> *Initial content derived from REPO_CONTEXT.md on ${today}. Review and update as needed.*
`;
    } catch {
        // File doesn't exist or can't be read
        return null;
    }
}

/**
 * Get PROJECT_CONTEXT.md content, deriving from REPO_CONTEXT.md if available, otherwise using template.
 *
 * @param repoContextPath - Path to REPO_CONTEXT.md (default: ".ai/context/repo_context/REPO_CONTEXT.md")
 * @param repoRoot - Root directory of the repository (defaults to process.cwd())
 * @param projectName - Name of the project (optional)
 * @returns PROJECT_CONTEXT.md content
 */
export async function getProjectContextContent(
    repoContextPath: string = ".ai/context/repo_context/REPO_CONTEXT.md",
    repoRoot?: string,
    projectName?: string,
): Promise<string> {
    // Try to derive from existing REPO_CONTEXT.md
    const derived = await deriveProjectContextFromRepoContext(repoContextPath, repoRoot);
    if (derived) {
        return derived;
    }

    // Fall back to template
    return getProjectContextTemplate(projectName);
}
